apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: tracing
build:
  artifacts:
    - image: k6
      context: .
      docker:
        dockerfile: docker/k6.Dockerfile
      sync:
        infer:
          - docker/k6/**/*
deploy:
  kustomize:
    paths:
      - docker/k8s/overlays/local
