apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug
  labels:
    app: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug
  template:
    metadata:
      labels:
        app: debug
    spec:
      containers:
        - name: debug
          image: golang:1.20
          tty: true
          ports:
            - containerPort: 28080
---
apiVersion: v1
kind: Service
metadata:
  name: debug
spec:
  selector:
    app: debug
  ports:
    - name: http-debug
      protocol: TCP
      appProtocol: http
      port: 28080
      targetPort: 28080
