apiVersion: 1
datasources:
  - name: loki
    type: loki
    access: proxy
    orgId: 1
    url: $LOKI_ENDPOINT
    basicAuth: false
    version: 1
  - name: prometheus
    type: prometheus
    access: proxy
    url: $PROMETHEUS_ENDPOINT
    basicAuth: false
    jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false
