apiVersion: 1
datasources:
  - name: loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: $LOKI_ENDPOINT
    basicAuth: false
    version: 1
  - name: prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: $PROMETHEUS_ENDPOINT
    basicAuth: false
    jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false
  - name: tempo # https://grafana.com/docs/grafana/latest/datasources/tempo/#provision-the-data-source
    type: tempo
    uid: tempo
    access: proxy
    orgId: 1
    url: $TEMPO_ENDPOINT
    basicAuth: false
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: loki
      tracesToMetrics:
        datasourceUid: prometheus
      serviceMap:
        datasourceUid: prometheus
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: loki
