apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: local
namespace: tracing-tutorial
resources:
  - ../../base
components:
  - ../../components/local
patchesStrategicMerge:
  - api.yaml
  - k6.yaml
