apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configMap.yaml
  - grafana.yaml
  - prometheus.yaml
  - loki.yaml
  - minio.yaml
  - tempo.yaml
  - api.yaml
  - k6.yaml
  - istio.yaml
configMapGenerator:
  - name: config
    files:
      - config/grafana.yml
      - config/loki.yml
      - config/prometheus.yml
      - config/promtail.yml
      - config/tempo.yml
