apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deployment
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      initContainers:
        - name: loki-init
          image: grafana/loki:2.7.3
          command:
            - chown
            - 10001:10001
            - /loki
        - name: wait-minio
          image: busybox
          command:
            - sh
            - -c
            - until nc -z minio 9000; do echo waiting for minio; sleep 2; done;
      containers:
        - name: loki
          image: grafana/loki:2.7.3
          command:
            - /usr/bin/loki
            - -config.file=/etc/config/loki.yml
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: minio_access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: minio_secret_key
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: loki_minio_endpoint
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/config
        - name: promtail
          image: grafana/promtail:2.7.3
          command:
            - /usr/bin/promtail
            - -config.file=/etc/config/promtail.yml
          volumeMounts:
            - name: config
              mountPath: /etc/config
      volumes:
        - name: config
          configMap:
            name: config
            items:
              - key: loki.yml
                path: loki.yml
              - key: promtail.yml
                path: promtail.yml
---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  selector:
    app: loki
  ports:
    - name: http-loki
      protocol: TCP
      appProtocol: http
      port: 3100
      targetPort: 3100
