apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: minio
          image: minio/minio
          command:
            - sh
            - -euc
            - |
              mkdir -p /data/loki-data && \
              mkdir -p /data/loki-ruler && \
              mkdir -p /data/tempo-data && \
              minio server /data
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: minio_access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: shared
                  key: minio_secret_key
            - name: MINIO_PROMETHEUS_AUTH_TYPE
              value: public
            - name: MINIO_UPDATE
              value: off
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - name: http-minio
      protocol: TCP
      appProtocol: http
      port: 9000
      targetPort: 9000
