apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo-deployment
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      initContainers:
        - name: wait-minio
          image: busybox
          command:
            - sh
            - -c
            - until nc -z minio 9000; do echo waiting for minio; sleep 2; done;
      containers:
        - name: tempo
          image: grafana/tempo:2.0.0
          command:
            - /tempo
            - -config.file=/etc/config/tempo.yml
          ports:
            - containerPort: 3200
            - containerPort: 14268 # jaeger
          volumeMounts:
            - name: config
              mountPath: /etc/config
      volumes:
        - name: config
          configMap:
            name: config
            items:
              - key: tempo.yml
                path: tempo.yml
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  ports:
    - name: http-tempo
      protocol: TCP
      appProtocol: http
      port: 3200
      targetPort: 3200
